### PR TITLE
added dynamic sleep features [did something wrong in github desktop at first]

### PR DESCRIPTION
**Pull request by 8bit-meiko**
addedpublic features:
'void idle()'
called in a infinite loop for task switching, sleeping and yield

'void sleep(int ms)'
sets value for thread to sleep, suspend it until that time (gets reactivated using idle loop (see above))

you need a
'extern void enter_sleep(int ms)'
in your ino file and add custom sleeping features to it, see examples/deepsleep for an example.

### CODE REVIEW

**Comment by ftrias** [comment]
Ramon, your pull request looks very sensible. There is only one issue I'm not sure about. After the call to enter_sleep(...), you assume that the Teensy actually slept for the entire time. But it could have been woken up by anything. I could be reading it wrong. In any case, it's a minor problem.

**Comment by 8bit-meiko** [comment]
this can be solved using the teensy's RTC, by comparing and storing start and end times (can be done in enter_sleep function), i'll leave that to the user on how he implements it (i want to keep as much flexibility as possible)

**Comment by 8bit-meiko** [comment]
added basic documentation to the code on how this can be done easily for simplicity, also including a return param in enter_sleep for actual time in ms spent asleep

**Comment by mjs513** [comment]
@ramonschepers - just gave your fork a shot ahead of official release (needed a sleep function :) ).  Anyway ran your example deepsleep.ino and received the following error:
```
C:\Users\CyberPalin\Documents\Arduino\libraries\TeensyThreads-master\TeensyThreads.cpp: In member function 'void Threads::idle()':

C:\Users\CyberPalin\Documents\Arduino\libraries\TeensyThreads-master\TeensyThreads.cpp:494:59: error: 'enter_sleep' was not declared in this scope
   volatile int time_spent_asleep = enter_sleep(substractor);
```
I also tried running blink.ino and received the same error.  

Running a T3.5 with TD1.4 and IDE 1.85 for reference. 

thanks mike

**Comment by 8bit-meiko** [comment]
ah, that's a small placement issue of the exern void and reference to the function in the library, thanks for noticing am pushing a working (and tested) commit now :)

**Comment by mjs513** [comment]
Can confirm it works, just gave it a try.  Is there a way for me to tell what thread to sleep, i.e., sleep(id, ms)?  Don't think so from what I saw but that was real quick.  Looks like it executes the sleep for the thread that it is in, I believe.

**Comment by 8bit-meiko** [comment]
Upontge sleep call, a thread it's sleep time is set before it is suspended, the actual sleeping happens from the idle call, which calculates how long to sleep. Note that I didn't test the code with the "legacy" delay code, so I'll advise to only use either the legacy delay, OR sleep/idle, but not a combination.

**Comment by mjs513** [comment]
Just as a FYI.  One of things that I have been doing with teensythreads is combining it with eventresponder.  I just ran a simple test with using your example sketch and my eventresponder sketch that uses timed events.  The sketch crashes at some point, i.e., continually loses the serial port and reconnects (keep hearing the beep on my windows machine).  The sketch keeps running, how do I know this, the lights keep blinking but there is a problem with eventresponder piece I think.  Here is the sketch if you want to give it a try:
```
#include <EventResponder.h>
#include <Arduino.h>
#include "TeensyThreads.h"
#include <Snooze.h>
#include <SnoozeBlock.h>

SnoozeTimer timer;
SnoozeBlock config(timer);

#define EVENT2_TIME 6000
#define EVENT3_TIME 1050
#define EVENT4_TIME 250
#define EVENT0_TIME 750

uint32_t event0_expected_time;
uint32_t event2_expected_time;
uint32_t event3_expected_time;
uint32_t event4_expected_time;

//EventResponder myevent;
EventResponder mytimerevent;
EventResponder mytimerevent2;
EventResponder mytimerevent3;
EventResponder mytimerevent4;

MillisTimer mytimer;
MillisTimer mytimer3;
MillisTimer mytimer2;
MillisTimer mytimer4;

const int LED = 13;
const int UserLED = 2;
bool test;
int tOn, tOff;

volatile int blinkcode = 0;

EventResponder led_switch;

//your sleeping funcion
int enter_sleep(int ms) {
  timer.setTimer(ms);//set sleep time in milliseconds  
  Snooze.hibernate( config ); //go to actual sleep
  //additional, one can use the RTC or a low power timer
  //to calculate actual time spent asleep and return the
  //value to the scheduler to calculate better times.
  return ms;
}


void heartbeat() {
  while (1) {
    threads.sleep(3000);
    digitalWriteFast(LED, !digitalRead(LED));
  }
}

void fastbeat() {
  while (1) {
    threads.sleep(1555);
    digitalWriteFast(UserLED, !digitalRead(UserLED));
  }
}

void setup() {
  while (!Serial && millis() < 4000) ;
  
  Serial.println("EventResponder test");

  //myevent.attach(dosomething);
  mytimerevent.attach(dotimer);
  mytimerevent2.attach(dotimer2);
  mytimerevent3.attach(dotimer3);
  mytimerevent4.attach(dotimer4);
  
  event0_expected_time = millis() +  EVENT0_TIME;
  mytimer2.beginRepeating( EVENT2_TIME, mytimerevent2);
  event2_expected_time = millis() +  EVENT2_TIME;
  mytimer3.beginRepeating(EVENT3_TIME, mytimerevent3);
  event3_expected_time = millis() +  EVENT3_TIME;
  mytimer4.beginRepeating(EVENT4_TIME, mytimerevent4);
  event4_expected_time = millis() +  EVENT4_TIME;

  pinMode(2, OUTPUT);
  digitalWriteFast(2, LOW); 
  pinMode(LED, OUTPUT);
  digitalWriteFast(LED, LOW);
  delay(2000);
  threads.addThread(heartbeat);
  threads.addThread(fastbeat);
}


void loop() {

  threads.idle();

  Serial.println("loop trigger dosomething");
  //myevent.triggerEvent();
  //delay(249);

}


void dosomething(EventResponderRef event)
{
  Serial.println("dosomething event");
  mytimer.begin(EVENT0_TIME, mytimerevent);
  event0_expected_time = millis() +  EVENT0_TIME;
}

void dotimer(EventResponderRef event)
{
  uint32_t t = millis();
  Serial.printf("%u - T0(%d)\n", t, (t >= event0_expected_time)? t - event0_expected_time : event0_expected_time - t);
  event0_expected_time  += EVENT0_TIME;}

void dotimer3(EventResponderRef event)
{
  blinkcode = 3;
  uint32_t t = millis();
  Serial.printf("%u - T3(%d)\n", t, (t >= event3_expected_time)? t - event3_expected_time : event3_expected_time - t);
  event3_expected_time  += EVENT3_TIME;
  //mytimerevent3.detach();
}

void dotimer4(EventResponderRef event)
{
  uint32_t t = millis();
  Serial.printf("%u - T4(%d)\n", t, (t >= event4_expected_time)? t - event4_expected_time : event4_expected_time - t);
  event4_expected_time  += EVENT4_TIME;
}

void dotimer2(EventResponderRef event)
{
  blinkcode = 0;
  uint32_t t = millis();
  Serial.printf("%u - T2(%d)\n", t, (t >= event2_expected_time)? t - event2_expected_time : event2_expected_time - t);
  event2_expected_time  += EVENT2_TIME;
}
```
You might want to check this post out as well because I was trying to convert it to using threads.sleep but couldn't get it to work, https://forum.pjrc.com/threads/44723-Arduino-Events?p=158615&viewfull=1#post158615.  I think bottom line is right now you won't be able to use thread.sleep with eventresponder.

thanks
Mike

**Comment by 8bit-meiko** [comment]
The serial losing connection is most probably due to the snow class shutting the USB communication down when entering deepsleep to save power, you can keep it awake by a snoozblock, see the snooze API for info on that :)

**Comment by mjs513** [comment]
Thanks.  I gave it a shot but have to do some more reading.  But snoozeblock seems to put it into lowpower 2mhz loop.  The other option was to use snoozeblock with usbserial driver class which I seem to having some problem getting to work.

**Comment by 8bit-meiko** [comment]
i had the same issues without teensythreads as well when i was developing with Snooze, so it must be some programming mistake in there.. ^^;

sorry for my late response though.

**Comment by ftrias** [comment]
I apologize for being over 2 years late in merging this but I didn't do it right when it was submitted.

**Pull request merged**
